### ISSUE TITLE
Error: servers must contain id, and username or configuration

### ISSUE THREAD

**Issue by Sneakometer** [s4u/maven-settings-action#132]
**Describe the bug**
The action fails to complete. Error

**To Reproduce**
```
name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.1
      
    - name: Maven Settings
      uses: s4u/maven-settings-action@v2.4.0
      with:
        servers: '[{"id": "myreponame", "username": "${{ secrets.USERNAME }}", "password": "${{ secrets.TOKEN }}"}]'
    
    - name: Install JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml`
```

**Expected behavior**
To setup settings.xml

**Additional context**
Github actions log:
```Prepare maven setings: /home/actionsrunner/.m2/settings.xml
Error: servers must contain id, and username or configuration```
