### ISSUE TITLE
401 Unauthorized when downloading from a private GitHub Packages repository

### ISSUE THREAD

**Issue by swimand** [s4u/maven-settings-action#260]
**Describe the bug**
I added a server configuration with my user and token, which I use for my own computer, and attempted to build a seperate private project, that is dependent of a private maven package in GitHub Packages. Installing the packages however leads to an issue where the package can not be found. 

**To Reproduce**
I have two private repositories in GitHub, repository A and repository B. 

Repository A deploys a maven package to GitHub Packages (which works without a problem).
Repository B references the package and is able to download and install it when debugging locally. 

However when running the following steps in a GitHub Action, I get the error `Could not resolve dependency...` 
```
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "github", "username": "${{ env.ACTION_USER }}", "password": "${{ secrets.PACKAGES_SECRET }}"}]'
          githubServer: false
      - run: mvn clean install -T 1C -DskipTests
```

Full error message is as follows: 
```
Failed to execute goal on project projectB: Could not resolve dependencies for project com.example:projectB:jar:0.0.1-SNAPSHOT: Could not find artifact com.example:projectA:jar:1.0.0-SNAPSHOT -> [Help 1]
```

**Expected behavior**
I expected the package to download without any issue.

**Additional context**
I have tried using the runners token, which I discovered does not have access to other private repositories. After this I tried creating a new token, which did not work either. Finally I provided the steps with my details and token, which I know to be working, as I use them locally, but still to no avail.
