### ISSUE TITLE
Unexpected token error when running s4u/maven-settings-action@v2.8.0

### ISSUE THREAD

**Issue by Ardesco** [s4u/maven-settings-action#293]
**Describe the bug**

I'm getting an unexpected token error:

>Run s4u/maven-settings-action@v2.8.0
>  with:
>    servers: [{"id": "sonatype-nexus-snapshots", "username": "***", "password": "***", "privateKey": "***", "passphrase": "***"}]
>    sonatypeSnapshots: false
>    apacheSnapshots: false
>    override: true
>    githubServer: true
>    oracleRepo: false
>  env:
>    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.19-7/x64
>    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.19-7/x64
>Prepare maven setings: /home/runner/.m[2](https://github.com/jmeter-maven-plugin/jmeter-maven-plugin/actions/runs/5521420641/jobs/10069493917#step:4:2)/settings.xml
>maven settings.xml already exists - override
>Error: Unexpected token 
 in JSON at position 1[7](https://github.com/jmeter-maven-plugin/jmeter-maven->plugin/actions/runs/5521420641/jobs/10069493917#step:4:7)2

The config I have is:

```
      - name: Set up Sonatype Snapshots Repository
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "sonatype-nexus-snapshots", "username": "${{ secrets.OSSRH_USERNAME }}", "password": "${{ secrets.OSSRH_TOKEN }}", "privateKey": "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}", "passphrase": "${{ secrets.MAVEN_GPG_PASSPHRASE }}"}]'
```

It looks like the position lines up with the `${{ secrets.MAVEN_GPG_PRIVATE_KEY }}` entry, but it;'s hard to work out why it's upset.

**To Reproduce**

Being reproduced on all my builds at the moment, but as I'm not sure of the exact cause I can't really provide repo instructions here.

**Expected behaviour**

My settings.xml setup should complete without issue.

**Additional context**

Could this be related to some characters in my GPG Private Key?  Possible escaping issue maybe?  I'm really looking for hints to help diagnose the problem.
