### ISSUE TITLE
Support for custom pluginRepositories

### ISSUE THREAD

**Issue by pwoodworth** [s4u/maven-settings-action#348]
### The Request
Custom plugin repositories should be configurable.

### The Solution
Configuration could look like the following example:
```yml
steps:
- uses: s4u/maven-settings-action@master
  with:
    pluginRepositories: >-
      [{
        "id": "repoId",
        "name": "repoName",
        "url": "url",
        "snapshots": {
          "enabled": true
        }
      }]
```

This should result in a settings.xml file like the following:
```xml
<profiles>
  <profile>
    <id>_custom_repositories_</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <repositories/>
    <pluginRepositories> 
      <pluginRepository>
        <id>repoId</id>
        <name>repoName</name>
        <url>url</url>
        <snapshots><enabled>true</enabled></snapshots>
      </pluginRepository>
    </pluginRepositories>
  </profile>
</profiles>
```
