### ISSUE TITLE
Error: servers must contain id, and username or configuration

### ISSUE THREAD

**Issue by ChaseMB00** [s4u/maven-settings-action#375]
**Describe the bug**
The s4u/maven-settings-action@v3.1.0 step fails with the error:
Error: servers must contain id, and username or configuration.
This occurs even though the servers input includes id, username, and password.

**To Reproduce**

Use the following build.yml GitHub Actions workflow:

```yaml
- name: Setup Settings
  uses: s4u/maven-settings-action@v3.1.0
  with:
    servers: '[{"id": "github-ntfy", "username": "${{ secrets.USERNAME }}", "password": "${{ secrets.TOKEN }}"}]'
    githubServer: false
```
Trigger the workflow with valid USERNAME and TOKEN secrets.

Observe the error message.

Expected behavior
The Maven settings file should be generated successfully using the provided server credentials, allowing Maven to authenticate with the ntfy repository.

Additional context

The secrets USERNAME and TOKEN are correctly configured in the repository. I use them locally to test.

![Image](https://github.com/user-attachments/assets/97eed7c4-9622-4e2b-82c9-fc4e0f9ba6b9)

The full error message is:

Error: servers must contain id, and username or configuration

To me it is unclear whether this is a bug in maven-settings-action or a misinterpretation of how secrets are interpolated in the JSON string input or just my incompetence.

**Comment by ChaseMB00** [comment]
Sorry my full build.yml is:
```yml
name: Reusable build workflow

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup Settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: '[{"id": "github-ntfy", "username": "${{ secrets.USERNAME }}", "password": "${{ secrets.TOKEN }}"}]'
          githubServer: false
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - run: |
          mkdir staging
          cp sms-authenticator/target/*.jar staging
          cp app-authenticator/target/*.jar staging
          cp enforce-mfa/target/*.jar staging
      - name: Create hash files
        run: |
          for jar in *.jar
          do
              sha512sum $jar | awk '{ print $1 }' > "${jar}.sha512"
          done
        working-directory: staging
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: staging

```

**Comment by MatthewRyanRead** [comment]
Try:

```yaml
- name: Setup Settings
  uses: s4u/maven-settings-action@v4.0.0
  env:
    USERNAME: ${{ secrets.USERNAME }}
    TOKEN: ${{ secrets.TOKEN }}
  with:
    servers: |
      [
        {
          "id": "github-ntfy",
          "username": "${env.USERNAME}",
          "password": "${env.TOKEN}"
        }
      ]
```

This is what works for me
