### ISSUE TITLE
Question on secrets

### ISSUE THREAD

**Issue by rnc** [s4u/maven-settings-action#77]
You have
```
steps:
- uses: s4u/maven-settings-action@v2.2.0
  with:
    servers: '[{"id": "serverId", "username": "username", "password": "password"}]'
```

Can secrets specified in the repository be passed into that? i.e. with `"${{ secrets.username }}` syntax?
