### ISSUE TITLE
servers merge

### ISSUE THREAD

**Issue by awhitford** [s4u/maven-settings-action#96]
The [setup-java](https://github.com/actions/setup-java) action provides support for configuring a `settings.xml`:
```yaml
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v1
      with: # running setup-java again overwrites the settings.xml
        java-version: 1.8
        server-id: maven # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
```

One should be able to use this action to _update_ `settings.xml`.  I believe the two options are `skip` and `override`, but ideally there is a `merge` option too so that one could use this action to _add_ a new `server` record to an existing `settings.xml`.
